2023-12-03 04:18:21.134854: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-03 04:18:21.174782: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-03 04:18:21.174820: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-03 04:18:21.174855: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-03 04:18:21.182858: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-03 04:18:22.074644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[EXECUTION] [04:18:23] Waiting before running function for 10 seconds.
[EXECUTION] [04:18:33] Sensors started
[STABLE CHECK] [04:18:36] Success: temperature is below threshold.
[MAIN] [04:18:36] Terminated sensors
[STABLE CHECK] [04:18:36] Waiting 20 seconds to reach stable state.

[STABLE CHECK] [04:18:56] Success: Machine is stable.
[EXECUTION] [04:18:56] Successfully reached stable state
Traceback (most recent call last):
  File "/home/saurabh/method-energy-dataset/projects/1_done/akanyaani_gpt-2-tensorflow2_patched/venv/lib64/python3.10/site-packages/tensorflow/python/framework/dtypes_method-level.py", line 244, in <module>
    trace_type.register_serializable(DType)
  File "/home/saurabh/miniconda3/lib/python3.10/site-packages/tensorflow/core/function/trace_type/serialization.py", line 58, in register_serializable
    raise ValueError(
ValueError: Existing Python class DType already has SerializedDType as its associated proto representation. Please ensure DType has a unique proto representation.
